//! The BOM review dialog and the pick&place generator dialog.
//!
//! Ports of libs/librepcb/editor/project/bomreviewdialog.{ui,cpp} and
//! libs/librepcb/editor/project/board/boardpickplacegeneratordialog.{ui,cpp}.
//!
//! Differences to upstream: no live part information (availability,
//! prices); the custom BOM attributes are stored in the project settings
//! (undoable) when the review dialog is closed with "OK" instead of while
//! typing. The pick&place files are generated by an output job run in a
//! worker thread (paths relative to the output directory
//! `output/{{VERSION}}/`, closing the dialog), and "Browse Output
//! Directory" is not offered.

use librepcb_core::export::{PickPlaceCsvWriter, PickPlaceSides};
use librepcb_core::job::{
    GerberX3OutputJob, ObjectSet, OutputJob, OutputJobKind, PickPlaceOutputJob,
};
use librepcb_core::project::board::BoardPickPlaceGenerator;
use librepcb_core::project::{AssemblyVariantId, BoardId, BomGenerator};
use librepcb_core::types::LengthUnit;
use librepcb_editor::commands::EditProjectSettings;
use librepcb_i18n::tr;

use super::{
    Applied, DialogContext, DialogOptions, FieldEvent, Form, FormDialog, ListButtons, ListItem,
    transaction,
};
use crate::project::AppProject;

const BRD: &str = "librepcb::editor::BomReviewDialog";
const PPD: &str = "librepcb::editor::BoardPickPlaceGeneratorDialog";

fn split_attributes(text: &str) -> Vec<String> {
    text.split(',')
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty())
        .collect()
}

fn variants(project: &AppProject) -> Vec<(AssemblyVariantId, String)> {
    project
        .shared()
        .lock()
        .project()
        .circuit()
        .assembly_variants()
        .iter()
        .map(|v| (AssemblyVariantId(v.uuid()), v.display_text()))
        .collect()
}

fn table_rows(values: &[Vec<String>], gray: impl Fn(usize) -> bool) -> Vec<ListItem> {
    values
        .iter()
        .enumerate()
        .map(|(i, row)| ListItem {
            enabled: !gray(i),
            ..ListItem::row(row.iter().map(|c| c.replace('\n', " ")).collect())
        })
        .collect()
}

// --- BOM review ---------------------------------------------------------------

/// The BOM review dialog (upstream `BomReviewDialog`).
pub struct BomReviewDialog {
    form: Form,
    boards: Vec<(BoardId, String)>,
    variants: Vec<(AssemblyVariantId, String)>,
}

impl BomReviewDialog {
    /// Opens the dialog, showing the BOM of `board` (`None`: without
    /// board).
    pub fn new(project: &AppProject, board: Option<BoardId>) -> Self {
        let (boards, attributes) = {
            let p = project.shared().lock();
            let prj = p.project();
            (
                prj.boards()
                    .iter()
                    .map(|b| (b.id(), b.name().to_string()))
                    .collect::<Vec<_>>(),
                prj.settings().custom_bom_attributes.clone(),
            )
        };
        let variants = variants(project);
        let mut form = Form::new(LengthUnit::Millimeters);
        let board_names: Vec<String> = std::iter::once(tr!(BRD, "None"))
            .chain(boards.iter().map(|(_, n)| n.clone()))
            .collect();
        form.choice(
            "board",
            tr!(BRD, "Board:"),
            &board_names,
            Some(
                board
                    .and_then(|b| boards.iter().position(|(id, _)| *id == b))
                    .map_or(0, |i| i + 1),
            ),
        );
        let variant_names: Vec<String> = variants.iter().map(|(_, n)| n.clone()).collect();
        form.choice(
            "variant",
            tr!(BRD, "Assembly Variant:"),
            &variant_names,
            (!variants.is_empty()).then_some(0),
        );
        form.set_enabled("variant", variants.len() > 1);
        form.text("attributes", tr!(BRD, "Attributes:"), attributes.join(", "));
        form.update("attributes", |f| {
            f.placeholder = tr!(BRD, "Comma-separated list of custom attributes (optional)").into();
        });
        form.list("bom", "", &[], &[], 14, ListButtons::default());
        form.note(
            "note",
            format!(
                "ⓘ {}",
                tr!(BRD, "Gray rows are not exported (do not mount).")
            ),
        );
        let dialog = Self {
            form,
            boards,
            variants,
        };
        dialog.update_bom(project);
        dialog
    }

    /// Upstream `updateBom()` and `updateTable()`.
    fn update_bom(&self, project: &AppProject) {
        let Some((variant, _)) = self
            .form
            .get_index("variant")
            .and_then(|i| self.variants.get(i))
        else {
            return;
        };
        let board = self
            .form
            .get_index("board")
            .and_then(|i| i.checked_sub(1))
            .and_then(|i| self.boards.get(i))
            .map(|(id, _)| *id);
        let p = project.shared().lock();
        let prj = p.project();
        let mut generator = BomGenerator::new(prj);
        generator.set_additional_attributes(split_attributes(&self.form.get_text("attributes")));
        let bom = generator.generate(board.and_then(|b| prj.board(b)), *variant);
        let mut writer = librepcb_core::export::BomCsvWriter::new(&bom);
        writer.set_include_non_mounted_parts(true);
        match writer.generate_csv() {
            Ok(csv) => {
                let rows = table_rows(csv.values(), |i| {
                    csv.values()
                        .get(i)
                        .and_then(|r| r.first())
                        .is_some_and(|q| q == "0")
                });
                self.form.update("bom", |f| {
                    f.columns = crate::models::vec_model(
                        csv.header().iter().map(|h| h.as_str().into()).collect(),
                    );
                });
                self.form.set_items("bom", &rows, None);
            }
            Err(e) => log::error!("Failed to update the BOM table: {e}"),
        }
    }

    /// The BOM table (tests): header and rows.
    pub fn table(&self) -> (Vec<String>, Vec<Vec<String>>) {
        let field = self.form.field("bom").unwrap_or_default();
        let header = slint::Model::iter(&field.columns)
            .map(|s| s.to_string())
            .collect();
        let rows = slint::Model::iter(&field.items)
            .map(|i| {
                slint::Model::iter(&i.cells)
                    .map(|s| s.to_string())
                    .collect()
            })
            .collect();
        (header, rows)
    }
}

impl FormDialog for BomReviewDialog {
    fn title(&self) -> String {
        tr!(BRD, "Review BOM")
    }

    form_accessors!();

    fn options(&self) -> DialogOptions {
        DialogOptions {
            apply: false,
            width: 800.0,
            label_width: 130.0,
            ..DialogOptions::default()
        }
    }

    fn field_event(&mut self, ctx: &DialogContext<'_>, id: &str, event: FieldEvent) {
        if matches!(id, "board" | "variant" | "attributes") && event == FieldEvent::Edited {
            self.update_bom(ctx.project);
        }
    }

    /// Stores the custom BOM attributes in the project settings.
    fn apply(&mut self, ctx: &DialogContext<'_>) -> Result<Applied, String> {
        let attributes = split_attributes(&self.form.get_text("attributes"));
        let unchanged = ctx
            .project
            .shared()
            .lock()
            .project()
            .settings()
            .custom_bom_attributes
            == attributes;
        if unchanged {
            return Ok(Applied::Nothing);
        }
        transaction(ctx.project, tr!(BRD, "Review BOM"), |e| {
            e.execute(EditProjectSettings {
                custom_bom_attributes: Some(attributes),
                ..EditProjectSettings::default()
            })
        })?;
        Ok(Applied::Project)
    }
}

// --- Pick&place generator -----------------------------------------------------------

/// The pick&place generator dialog (upstream
/// `BoardPickPlaceGeneratorDialog`).
pub struct PickPlaceGeneratorDialog {
    form: Form,
    board: BoardId,
    variants: Vec<(AssemblyVariantId, String)>,
}

impl PickPlaceGeneratorDialog {
    /// Opens the dialog for a board; `None` if it does not exist.
    pub fn new(project: &AppProject, board: BoardId) -> Option<Self> {
        let name = project
            .shared()
            .lock()
            .project()
            .board(board)?
            .name()
            .to_string();
        let variants = variants(project);
        let mut form = Form::new(LengthUnit::Millimeters);
        form.label("board", tr!(PPD, "Board:"), name);
        let variant_names: Vec<String> = variants.iter().map(|(_, n)| n.clone()).collect();
        form.choice(
            "variant",
            tr!(PPD, "Assembly Variant:"),
            &variant_names,
            (!variants.is_empty()).then_some(0),
        );
        form.set_enabled("variant", variants.len() > 1);
        form.radio(
            "format",
            tr!(PPD, "Format:"),
            &[
                tr!(PPD, "CSV with metadata*"),
                tr!(PPD, "CSV without metadata"),
                tr!(PPD, "Gerber X3"),
            ],
            0,
        );
        let mut path = "assembly/{{PROJECT}}_PnP".to_owned();
        if variants.len() > 1 {
            path += "_{{VARIANT}}";
        }
        form.checkbox("top", "", tr!(PPD, "Top Devices:"), true);
        form.text("top_path", "", format!("{path}_TOP.csv"));
        form.checkbox("bottom", "", tr!(PPD, "Bottom Devices:"), true);
        form.text("bottom_path", "", format!("{path}_BOT.csv"));
        form.note(
            "footnote",
            tr!(
                PPD,
                "*) Adds additional information to the files, but might cause issues with some CSV readers."
            ),
        );
        form.list("data", "", &[], &[], 10, ListButtons::default());
        form.note(
            "note",
            format!(
                "ⓘ {}",
                tr!(PPD, "Gray rows are not exported (do not mount).")
            ),
        );
        let dialog = Self {
            form,
            board,
            variants,
        };
        dialog.update_data(project);
        Some(dialog)
    }

    fn variant(&self) -> Option<AssemblyVariantId> {
        self.form
            .get_index("variant")
            .and_then(|i| self.variants.get(i))
            .map(|(id, _)| *id)
    }

    /// Upstream `updateData()`: the table of all parts.
    fn update_data(&self, project: &AppProject) {
        let Some(variant) = self.variant() else {
            return;
        };
        let p = project.shared().lock();
        let data = BoardPickPlaceGenerator::new(p.project(), self.board, variant)
            .and_then(|g| g.generate());
        let data = match data {
            Ok(data) => data,
            Err(e) => {
                log::error!("Failed to update the pick&place table: {e}");
                return;
            }
        };
        let mut writer = PickPlaceCsvWriter::new(&data, crate::app::APP_VERSION);
        writer.set_include_non_mounted_parts(true);
        writer.set_include_metadata_comment(false);
        writer.set_board_sides(PickPlaceSides::Both);
        match writer.generate_csv() {
            Ok(csv) => {
                let rows = table_rows(csv.values(), |i| {
                    data.items().get(i).is_none_or(|item| !item.mount)
                });
                self.form.update("data", |f| {
                    f.columns = crate::models::vec_model(
                        csv.header().iter().map(|h| h.as_str().into()).collect(),
                    );
                });
                self.form.set_items("data", &rows, None);
            }
            Err(e) => log::error!("Failed to update the pick&place table: {e}"),
        }
    }

    /// Upstream `setFileExtension()`.
    fn set_extension(&self, extension: &str) {
        for id in ["top_path", "bottom_path"] {
            let text = self.form.get_text(id);
            if let Some((base, ext)) = text.rsplit_once('.')
                && !ext.eq_ignore_ascii_case(extension)
            {
                self.form.set_text(id, format!("{base}.{extension}"));
            }
        }
    }

    /// The job generating the files (tests).
    pub fn job(&self) -> Result<OutputJob, String> {
        let f = &self.form;
        let variant = self
            .variant()
            .ok_or_else(|| "No assembly variant.".to_owned())?;
        let boards = ObjectSet::custom([self.board]);
        let variants = ObjectSet::custom([variant]);
        let (top, bottom) = (f.get_checked("top"), f.get_checked("bottom"));
        let (top_path, bottom_path) = (
            f.get_text("top_path").trim().to_owned(),
            f.get_text("bottom_path").trim().to_owned(),
        );
        Ok(if f.get_index("format") == Some(2) {
            let mut job = OutputJob::new_default::<GerberX3OutputJob>();
            if let OutputJobKind::GerberX3(j) = job.kind_mut() {
                j.boards = boards;
                j.assembly_variants = variants;
                j.enable_components_top = top;
                j.enable_components_bot = bottom;
                j.output_path_components_top = top_path;
                j.output_path_components_bot = bottom_path;
                j.enable_glue_top = false;
                j.enable_glue_bot = false;
            }
            job
        } else {
            let mut job = OutputJob::new_default::<PickPlaceOutputJob>();
            if let OutputJobKind::PickPlace(j) = job.kind_mut() {
                j.boards = boards;
                j.assembly_variants = variants;
                j.include_comment = f.get_index("format") == Some(0);
                j.create_top = top;
                j.create_bottom = bottom;
                j.create_both = false;
                j.output_path_top = top_path;
                j.output_path_bottom = bottom_path;
            }
            job
        })
    }
}

impl FormDialog for PickPlaceGeneratorDialog {
    fn title(&self) -> String {
        tr!(PPD, "Generate Pick&Place Data")
    }

    form_accessors!();

    fn options(&self) -> DialogOptions {
        DialogOptions {
            apply: false,
            ok_text: Some(tr!(PPD, "&Generate").replace('&', "")),
            width: 800.0,
            label_width: 130.0,
            ..DialogOptions::default()
        }
    }

    fn field_event(&mut self, ctx: &DialogContext<'_>, id: &str, event: FieldEvent) {
        match (id, event) {
            ("variant", FieldEvent::Edited) => self.update_data(ctx.project),
            ("format", FieldEvent::Edited) => {
                let gerber = self.form.get_index("format") == Some(2);
                self.set_extension(if gerber { "gbr" } else { "csv" });
            }
            _ => {}
        }
    }

    fn apply(&mut self, _ctx: &DialogContext<'_>) -> Result<Applied, String> {
        Ok(Applied::RunJobs {
            title: self.title(),
            jobs: vec![self.job()?],
        })
    }
}
