[package]
name = "librepcb-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bitflags = "2.13.2"
chrono = { version = "0.4.45", default-features = false, features = ["std", "clock"] }
clipper = { version = "0.1.0", path = "../clipper" }
libm = "0.2.16"
librepcb-i18n = { version = "0.1.0", path = "../librepcb-i18n" }
regex = "1.13.1"
thiserror = "2.0.21"
unicode-general-category = "1.1.0"
unicode-normalization = "0.1.25"
uuid = { version = "1.26.1", features = ["v4"] }

[lints]
workspace = true
