//! Port of libs/librepcb/kicadimport: import of KiCad libraries.
//!
//! - [`types`]: the KiCad symbol library and footprint file formats.
//! - [`KiCadTypeConverter`]: conversion of KiCad types into LibrePCB types.
//! - [`KiCadLibraryConverter`]: conversion of footprints and symbols into
//!   LibrePCB library elements.
//! - [`KiCadLibraryImport`]: the library import (scan, parse, element
//!   selection with dependencies, options, import into a library
//!   directory).

mod error;
mod library_converter;
mod library_import;
mod type_converter;
pub mod types;

use librepcb_core::fileio::FilePath;
use librepcb_core::types::Uuid;
use librepcb_core::workspace::{ElementKind, LibraryDb};

pub use error::{Error, Result};
pub use library_converter::{KiCadLibraryConverter, KiCadLibraryConverterSettings};
pub use library_import::{
    CATEGORY_NAME, COMPATIBLE_KICAD_VERSION, FootprintLibrary, ImportFootprint, ImportGate,
    ImportState, ImportSymbol, KiCadLibraryImport, NAME_PREFIX, Package3dLibrary, ScanResult,
    SymbolLibrary, merge_symbol_gates,
};
pub use type_converter::{KiCadTypeConverter, Line, LineGroup, PadReplacements};

/// Lookup of elements imported before, identified by their "generated_by"
/// key (upstream: `WorkspaceLibraryDb::getGenerated()` and `getLatest()`).
/// Lookup errors are treated like "not found".
pub trait ImportedElementLookup: Send + Sync {
    /// Returns the UUIDs of the elements of `kind` generated by
    /// `generated_by`.
    fn generated(&self, kind: ElementKind, generated_by: &str) -> Vec<Uuid>;

    /// Returns the directory of the latest version of an element.
    fn latest(&self, kind: ElementKind, uuid: Uuid) -> Option<FilePath>;
}

/// A lookup without any imported elements (e.g. for imports without
/// workspace).
#[derive(Debug, Clone, Copy, Default)]
pub struct NoImportedElements;

impl ImportedElementLookup for NoImportedElements {
    fn generated(&self, _kind: ElementKind, _generated_by: &str) -> Vec<Uuid> {
        Vec::new()
    }

    fn latest(&self, _kind: ElementKind, _uuid: Uuid) -> Option<FilePath> {
        None
    }
}

impl ImportedElementLookup for LibraryDb {
    fn generated(&self, kind: ElementKind, generated_by: &str) -> Vec<Uuid> {
        match LibraryDb::generated(self, kind, generated_by) {
            Ok(uuids) => uuids.into_iter().collect(),
            Err(e) => {
                log::error!("Failed to get imported elements: {e}");
                Vec::new()
            }
        }
    }

    fn latest(&self, kind: ElementKind, uuid: Uuid) -> Option<FilePath> {
        LibraryDb::latest(self, kind, uuid).ok().flatten()
    }
}
