[package]
name = "i18n-check"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
i-slint-backend-testing = "1.18.1"
librepcb-i18n = { version = "0.1.0", path = "../../crates/librepcb-i18n" }
slint = "1.18.1"

# Standalone: not part of the main workspace.
[workspace]

[build-dependencies]
librepcb-i18n = { version = "0.1.0", path = "../../crates/librepcb-i18n" }
slint-build = "1.18.1"
