[package]
name = "librepcb-autoroute"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
librepcb-core = { version = "0.1.0", path = "../librepcb-core" }
librepcb-i18n = { version = "0.1.0", path = "../librepcb-i18n" }
rstar = "0.13.0"
static_assertions = "1.1.0"
thiserror = "2.0.21"

[lints]
workspace = true
