//! Converts LibrePCB's Qt `.ts` translation files (`../LibrePCB/i18n`) into
//! gettext catalogs usable by both Slint's bundled translations and
//! `librepcb_i18n`:
//!
//! * `<out>/<lang>/LC_MESSAGES/<domain>.po` for each translated language,
//! * `<out>/<domain>.pot` template from the source-language file (`en_US`).
//!
//! Usage: `cargo run -p ts2po -- [--ts-dir DIR] [--slint-root DIR] [--out DIR] [--domain NAME]`
//!
//! See the module docs of `convert`, `placeholders` and `languages` for the
//! conversion rules.

mod convert;
mod languages;
mod placeholders;
mod po;
mod slint_src;
mod ts;

use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result, bail};

use crate::convert::{Report, convert};
use crate::languages::{normalize_language, plural_rule};
use crate::slint_src::SlintSources;

struct Args {
    ts_dir: PathBuf,
    slint_root: PathBuf,
    out: PathBuf,
    domain: String,
}

fn parse_args() -> Result<Args> {
    let mut args = Args {
        ts_dir: "../LibrePCB/i18n".into(),
        slint_root: "../LibrePCB".into(),
        out: "lang".into(),
        domain: "librepcb".into(),
    };
    let mut it = std::env::args().skip(1);
    while let Some(arg) = it.next() {
        let mut value = || {
            it.next()
                .with_context(|| format!("missing value for {arg}"))
        };
        match arg.as_str() {
            "--ts-dir" => args.ts_dir = value()?.into(),
            "--slint-root" => args.slint_root = value()?.into(),
            "--out" => args.out = value()?.into(),
            "--domain" => args.domain = value()?,
            "-h" | "--help" => {
                println!(
                    "Usage: ts2po [--ts-dir DIR] [--slint-root DIR] [--out DIR] [--domain NAME]"
                );
                std::process::exit(0);
            }
            other => bail!("unknown argument {other:?}"),
        }
    }
    Ok(args)
}

const HEADER_COMMENT: &str = "LibrePCB translations, generated by tools/ts2po from \
upstream i18n/librepcb_*.ts.\nDo not edit: translations are maintained on Transifex.";

fn main() -> Result<()> {
    let args = parse_args()?;
    let mut ts_files: Vec<PathBuf> = std::fs::read_dir(&args.ts_dir)
        .with_context(|| format!("reading {}", args.ts_dir.display()))?
        .map(|e| e.map(|e| e.path()))
        .collect::<Result<_, _>>()?;
    ts_files.retain(|p| p.extension().is_some_and(|e| e == "ts"));
    ts_files.sort();
    if ts_files.is_empty() {
        bail!("no .ts files in {}", args.ts_dir.display());
    }

    let mut slint = SlintSources::new(Some(args.slint_root.clone()));
    println!(
        "{:<8} {:>8} {:>10} {:>6} {:>12}",
        "lang", "entries", "translated", "fuzzy", "untranslated"
    );
    for path in &ts_files {
        let xml =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        let ts = ts::parse(&xml).with_context(|| format!("parsing {}", path.display()))?;
        let code = if ts.language.is_empty() {
            language_from_filename(path)?
        } else {
            ts.language.clone()
        };
        let tag = normalize_language(&code);
        let is_source = tag.split('-').next() == Some(ts.source_language.as_str())
            || (ts.source_language.is_empty() && tag.starts_with("en"));
        let mut report = Report::default();

        if is_source {
            let entries = convert(&ts.messages, None, &mut slint, &mut report);
            if ts
                .messages
                .iter()
                .any(|m| !m.translation.is_empty() || m.numerus_forms.iter().any(|f| !f.is_empty()))
            {
                eprintln!(
                    "warning: {} (source language) contains translations; ignored",
                    path.display()
                );
            }
            let header = [
                ("Project-Id-Version", "LibrePCB"),
                ("MIME-Version", "1.0"),
                ("Content-Type", "text/plain; charset=UTF-8"),
                ("Content-Transfer-Encoding", "8bit"),
                ("Plural-Forms", "nplurals=INTEGER; plural=EXPRESSION;"),
                ("X-Generator", "ts2po"),
            ];
            let out = args.out.join(format!("{}.pot", args.domain));
            write_file(&out, &po::write(HEADER_COMMENT, &header, &entries))?;
            println!(
                "{:<8} {:>8}  (template {})",
                tag,
                entries.len(),
                out.display()
            );
        } else {
            let rule = plural_rule(&tag)
                .with_context(|| format!("no plural rule for language {tag:?}"))?;
            let entries = convert(&ts.messages, Some(&rule), &mut slint, &mut report);
            let header = [
                ("Project-Id-Version", "LibrePCB"),
                ("Language", tag.as_str()),
                ("MIME-Version", "1.0"),
                ("Content-Type", "text/plain; charset=UTF-8"),
                ("Content-Transfer-Encoding", "8bit"),
                ("Plural-Forms", rule.plural_forms),
                ("X-Generator", "ts2po"),
            ];
            let out = args
                .out
                .join(&tag)
                .join("LC_MESSAGES")
                .join(format!("{}.po", args.domain));
            write_file(&out, &po::write(HEADER_COMMENT, &header, &entries))?;
            let translated = entries.iter().filter(|e| e.is_translated()).count();
            let fuzzy = entries.iter().filter(|e| e.fuzzy).count();
            println!(
                "{:<8} {:>8} {:>10} {:>6} {:>12}",
                tag,
                entries.len(),
                translated,
                fuzzy,
                entries.len() - translated - fuzzy
            );
        }
        for w in &report.warnings {
            eprintln!("warning [{tag}]: {w}");
        }
        if !report.slint_heuristic.is_empty() {
            eprintln!(
                "warning [{tag}]: {} Slint strings not found in sources, msgid reconstructed heuristically: {:?}",
                report.slint_heuristic.len(),
                report.slint_heuristic
            );
        }
        if report.obsolete > 0 || report.merged_duplicates > 0 {
            eprintln!(
                "info [{tag}]: dropped {} obsolete, merged {} duplicates, {} Slint msgids recovered from sources",
                report.obsolete, report.merged_duplicates, report.slint_recovered
            );
        }
    }
    Ok(())
}

fn language_from_filename(path: &Path) -> Result<String> {
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or_default();
    stem.strip_prefix("librepcb_")
        .map(str::to_owned)
        .with_context(|| format!("cannot determine language of {}", path.display()))
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(path, content).with_context(|| format!("writing {}", path.display()))
}
