//! Port of libs/librepcb/core/export/interactivehtmlbom.{h,cpp} (and of
//! upstream's FFI wrapper libs/librepcb/rust-core/src/ffi/ibom_ffi.rs).
//!
//! Like upstream, the HTML page is generated by the
//! [`interactive-html-bom`](https://crates.io/crates/interactive-html-bom)
//! crate (the same version as upstream, so the output is identical).
//! [`InteractiveHtmlBom`] converts LibrePCB's types into the crate's
//! (millimeters as `f32`, Y axis pointing down) exactly like upstream's C++
//! wrapper does.
//!
//! Differences to upstream: [`InteractiveHtmlBom::add_footprint()`] returns
//! an error if a pad outline cannot be calculated (upstream's `noexcept`
//! method would terminate the application).

use std::fmt;
use std::str::FromStr;

use interactive_html_bom as ibom;

use super::{Error, Result};
use crate::geometry::{PadGeometry, PadHole, Path};
use crate::serialization::{self, FromSExpression, SExpression, ToSExpression};
use crate::types::{self, Angle, Length, Orientation, Point, PositiveLength, UnsignedLength};
use crate::utils::toolbox;
use crate::utils::transform::Transform;

/// Layout of the interactive HTML BOM (upstream
/// `InteractiveHtmlBom::ViewMode`).
///
/// Serde: the file format token (`"bom_only"`, `"left_right"`,
/// `"top_bottom"`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum InteractiveHtmlBomViewMode {
    /// Only the BOM table.
    BomOnly,
    /// BOM table left, board views right.
    #[default]
    LeftRight,
    /// BOM table on top, board views below.
    TopBottom,
}

impl InteractiveHtmlBomViewMode {
    /// Returns the file format token.
    pub fn to_str(self) -> &'static str {
        match self {
            Self::BomOnly => "bom_only",
            Self::LeftRight => "left_right",
            Self::TopBottom => "top_bottom",
        }
    }
}

impl fmt::Display for InteractiveHtmlBomViewMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.to_str())
    }
}

impl FromStr for InteractiveHtmlBomViewMode {
    type Err = types::Error;
    fn from_str(s: &str) -> Result<Self, types::Error> {
        [Self::BomOnly, Self::LeftRight, Self::TopBottom]
            .into_iter()
            .find(|v| v.to_str() == s)
            .ok_or_else(|| types::Error::UnknownInteractiveHtmlBomViewMode(s.to_owned()))
    }
}

crate::utils::serde_string::serde_string!(InteractiveHtmlBomViewMode);

impl ToSExpression for InteractiveHtmlBomViewMode {
    fn to_sexpression(&self) -> SExpression {
        SExpression::token(self.to_str())
    }
}

impl FromSExpression for InteractiveHtmlBomViewMode {
    fn from_sexpression(node: &SExpression) -> serialization::Result<Self> {
        Ok(node.value()?.parse()?)
    }
}

/// Which pin 1 pads are highlighted in the interactive HTML BOM (upstream
/// `InteractiveHtmlBom::HighlightPin1Mode`).
///
/// Serde: the file format token (`"none"`, `"selected"`, `"all"`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum InteractiveHtmlBomHighlightPin1Mode {
    /// No highlighting.
    #[default]
    None,
    /// Pin 1 of selected components.
    Selected,
    /// Pin 1 of all components.
    All,
}

impl InteractiveHtmlBomHighlightPin1Mode {
    /// Returns the file format token.
    pub fn to_str(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Selected => "selected",
            Self::All => "all",
        }
    }
}

impl fmt::Display for InteractiveHtmlBomHighlightPin1Mode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.to_str())
    }
}

impl FromStr for InteractiveHtmlBomHighlightPin1Mode {
    type Err = types::Error;
    fn from_str(s: &str) -> Result<Self, types::Error> {
        [Self::None, Self::Selected, Self::All]
            .into_iter()
            .find(|v| v.to_str() == s)
            .ok_or_else(|| types::Error::UnknownInteractiveHtmlBomHighlightPin1Mode(s.to_owned()))
    }
}

crate::utils::serde_string::serde_string!(InteractiveHtmlBomHighlightPin1Mode);

impl ToSExpression for InteractiveHtmlBomHighlightPin1Mode {
    fn to_sexpression(&self) -> SExpression {
        SExpression::token(self.to_str())
    }
}

impl FromSExpression for InteractiveHtmlBomHighlightPin1Mode {
    fn from_sexpression(node: &SExpression) -> serialization::Result<Self> {
        Ok(node.value()?.parse()?)
    }
}

impl From<InteractiveHtmlBomViewMode> for ibom::ViewMode {
    fn from(mode: InteractiveHtmlBomViewMode) -> Self {
        match mode {
            InteractiveHtmlBomViewMode::BomOnly => Self::BomOnly,
            InteractiveHtmlBomViewMode::LeftRight => Self::LeftRight,
            InteractiveHtmlBomViewMode::TopBottom => Self::TopBottom,
        }
    }
}

impl From<InteractiveHtmlBomHighlightPin1Mode> for ibom::HighlightPin1Mode {
    fn from(mode: InteractiveHtmlBomHighlightPin1Mode) -> Self {
        match mode {
            InteractiveHtmlBomHighlightPin1Mode::None => Self::None,
            InteractiveHtmlBomHighlightPin1Mode::Selected => Self::Selected,
            InteractiveHtmlBomHighlightPin1Mode::All => Self::All,
        }
    }
}

/// Copper side of the board (upstream `InteractiveHtmlBom::Layer`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InteractiveHtmlBomLayer {
    /// Top side.
    Top,
    /// Bottom side.
    Bottom,
}

impl From<InteractiveHtmlBomLayer> for ibom::Layer {
    fn from(layer: InteractiveHtmlBomLayer) -> Self {
        match layer {
            InteractiveHtmlBomLayer::Top => Self::Front,
            InteractiveHtmlBomLayer::Bottom => Self::Back,
        }
    }
}

/// Board side(s) of a BOM row (upstream `InteractiveHtmlBom::Sides`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InteractiveHtmlBomSides {
    /// Top side.
    Top,
    /// Bottom side.
    Bottom,
    /// Both sides.
    Both,
}

/// Kind of a drawing (upstream `InteractiveHtmlBom::DrawingKind`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InteractiveHtmlBomDrawingKind {
    /// Any graphics.
    Polygon,
    /// Designator text of a component.
    ReferenceText,
    /// Value text of a component.
    ValueText,
}

impl From<InteractiveHtmlBomDrawingKind> for ibom::DrawingKind {
    fn from(kind: InteractiveHtmlBomDrawingKind) -> Self {
        match kind {
            InteractiveHtmlBomDrawingKind::Polygon => Self::Polygon,
            InteractiveHtmlBomDrawingKind::ReferenceText => Self::ReferenceText,
            InteractiveHtmlBomDrawingKind::ValueText => Self::ValueText,
        }
    }
}

/// Layer of a drawing (upstream `InteractiveHtmlBom::DrawingLayer`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InteractiveHtmlBomDrawingLayer {
    /// Board outline.
    Edge,
    /// Top silkscreen.
    SilkscreenFront,
    /// Bottom silkscreen.
    SilkscreenBack,
    /// Top fabrication (documentation).
    FabricationFront,
    /// Bottom fabrication (documentation).
    FabricationBack,
}

impl From<InteractiveHtmlBomDrawingLayer> for ibom::DrawingLayer {
    fn from(layer: InteractiveHtmlBomDrawingLayer) -> Self {
        match layer {
            InteractiveHtmlBomDrawingLayer::Edge => Self::Edge,
            InteractiveHtmlBomDrawingLayer::SilkscreenFront => Self::SilkscreenFront,
            InteractiveHtmlBomDrawingLayer::SilkscreenBack => Self::SilkscreenBack,
            InteractiveHtmlBomDrawingLayer::FabricationFront => Self::FabricationFront,
            InteractiveHtmlBomDrawingLayer::FabricationBack => Self::FabricationBack,
        }
    }
}

/// A footprint pad (upstream `InteractiveHtmlBom::Pad`).
#[derive(Debug, Clone, PartialEq)]
pub struct InteractiveHtmlBomPad {
    /// Whether the pad has copper on the top side.
    pub on_top: bool,
    /// Whether the pad has copper on the bottom side.
    pub on_bottom: bool,
    /// Position on the board.
    pub position: Point,
    /// Rotation on the board.
    pub rotation: Angle,
    /// Whether the geometry is mirrored.
    pub mirror_geometry: bool,
    /// Geometries on the solder side (only the first one is drawn).
    pub geometries: Vec<PadGeometry>,
    /// Holes (only the first one is drawn).
    pub holes: Vec<PadHole>,
    /// Net name, if any.
    pub net_name: Option<String>,
    /// Whether this is pin 1.
    pub pin1: bool,
}

/// Converts a length to millimeters as `f32` (upstream passes
/// `Length::toMm()` to a `float` parameter).
fn mm(length: Length) -> f32 {
    length.to_mm() as f32
}

/// Converts an angle to degrees as `f32`.
fn deg(angle: Angle) -> f32 {
    angle.to_deg() as f32
}

/// Converts a point to millimeters with the Y axis pointing down.
///
/// Like upstream, the floating point value is negated (not the length), so
/// a zero Y coordinate becomes `-0`, which is written as such.
fn pos(p: Point) -> (f32, f32) {
    (mm(p.x), -mm(p.y))
}

/// Builder of an interactive HTML BOM (upstream `InteractiveHtmlBom`).
pub struct InteractiveHtmlBom {
    inner: ibom::InteractiveHtmlBom,
}

impl fmt::Debug for InteractiveHtmlBom {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("InteractiveHtmlBom")
            .field("footprints", &self.inner.footprints.len())
            .finish_non_exhaustive()
    }
}

static_assertions::assert_impl_all!(InteractiveHtmlBom: Send, Sync);

impl InteractiveHtmlBom {
    /// Creates a BOM with the project metadata and the bounding box of the
    /// board. Like upstream, `top_left` and `bottom_right` are actually the
    /// bottom left and top right corners (LibrePCB coordinates, Y axis
    /// pointing up).
    pub fn new(
        title: &str,
        company: &str,
        revision: &str,
        date: &str,
        top_left: Point,
        bottom_right: Point,
    ) -> Self {
        Self {
            inner: ibom::InteractiveHtmlBom::new(
                title,
                company,
                revision,
                date,
                (mm(top_left.x), -mm(bottom_right.y)),
                (mm(bottom_right.x), -mm(top_left.y)),
            ),
        }
    }

    /// Sets the view configuration (upstream `setViewConfig()`).
    pub fn set_view_config(
        &mut self,
        mode: InteractiveHtmlBomViewMode,
        highlight_pin1: InteractiveHtmlBomHighlightPin1Mode,
        dark: bool,
    ) {
        self.inner.view_mode = mode.into();
        self.inner.highlight_pin1 = highlight_pin1.into();
        self.inner.dark_mode = dark;
    }

    /// Sets the board rotation (upstream `setBoardRotation()`).
    pub fn set_board_rotation(&mut self, angle: Angle, offset_back: bool) {
        self.inner.board_rotation = deg(angle);
        self.inner.offset_back_rotation = offset_back;
    }

    /// Sets the silkscreen visibility.
    pub fn set_show_silkscreen(&mut self, show: bool) {
        self.inner.show_silkscreen = show;
    }

    /// Sets the fabrication layers visibility.
    pub fn set_show_fabrication(&mut self, show: bool) {
        self.inner.show_fabrication = show;
    }

    /// Sets the pads visibility.
    pub fn set_show_pads(&mut self, show: bool) {
        self.inner.show_pads = show;
    }

    /// Sets the names of the check box columns.
    pub fn set_check_boxes(&mut self, names: Vec<String>) {
        self.inner.checkboxes = names;
    }

    /// Sets the names of the BOM fields.
    pub fn set_fields(&mut self, fields: Vec<String>) {
        self.inner.fields = fields;
    }

    /// Adds a drawing (upstream `addDrawing()`).
    pub fn add_drawing(
        &mut self,
        kind: InteractiveHtmlBomDrawingKind,
        layer: InteractiveHtmlBomDrawingLayer,
        path: &Path,
        width: UnsignedLength,
        filled: bool,
    ) {
        self.inner.drawings.push(ibom::Drawing::new(
            kind.into(),
            layer.into(),
            &path.to_svg_path_mm(),
            mm(*width),
            filled,
        ));
    }

    /// Adds a track (upstream `addTrack()`).
    pub fn add_track(
        &mut self,
        layer: InteractiveHtmlBomLayer,
        start: Point,
        end: Point,
        width: PositiveLength,
        net_name: Option<&str>,
    ) {
        self.inner.tracks.push(ibom::Track::new(
            layer.into(),
            pos(start),
            pos(end),
            mm(*width),
            net_name,
        ));
    }

    /// Adds a via (upstream `addVia()`).
    pub fn add_via(
        &mut self,
        layers: &[InteractiveHtmlBomLayer],
        position: Point,
        diameter: PositiveLength,
        drill_diameter: PositiveLength,
        net_name: Option<&str>,
    ) {
        let layers: Vec<ibom::Layer> = layers.iter().map(|l| (*l).into()).collect();
        self.inner.vias.push(ibom::Via::new(
            &layers,
            pos(position),
            mm(*diameter),
            mm(*drill_diameter),
            net_name,
        ));
    }

    /// Adds a plane fragment (upstream `addPlaneFragment()`).
    pub fn add_plane_fragment(
        &mut self,
        layer: InteractiveHtmlBomLayer,
        outline: &Path,
        net_name: Option<&str>,
    ) {
        let mut outline = outline.clone();
        outline.close();
        self.inner.zones.push(ibom::Zone::new(
            layer.into(),
            &outline.to_svg_path_mm(),
            net_name,
        ));
    }

    /// Adds a footprint and returns its ID (upstream `addFootprint()`).
    ///
    /// Like upstream, `top_left` and `bottom_right` are actually the bottom
    /// left and top right corners of the footprint's bounding box.
    #[allow(clippy::too_many_arguments)] // Upstream API.
    pub fn add_footprint(
        &mut self,
        layer: InteractiveHtmlBomLayer,
        position: Point,
        rotation: Angle,
        top_left: Point,
        bottom_right: Point,
        mount: bool,
        fields: &[String],
        pads: &[InteractiveHtmlBomPad],
    ) -> Result<usize> {
        let mut ibom_pads = Vec::with_capacity(pads.len());
        for pad in pads {
            // Determine hole.
            let mut drill = None;
            let mut hole_offset = Point::ORIGIN;
            let mut hole_rotation = Angle::DEG0;
            if let Some(hole) = pad.holes.first() {
                let vertices = hole.path().vertices();
                if let [v0, v1, ..] = vertices {
                    let (p0, p1) = (v0.pos, v1.pos);
                    hole_rotation = toolbox::angle_between_points(p0, p1)
                        * if pad.mirror_geometry { -1 } else { 1 };
                    hole_offset = (p0 + p1) / 2;
                    let width = *(p1 - p0).length() + *hole.diameter();
                    drill = Some((mm(width), mm(*hole.diameter())));
                } else {
                    hole_offset = vertices.first().map_or(Point::ORIGIN, |v| v.pos);
                    drill = Some((mm(*hole.diameter()), mm(*hole.diameter())));
                }
            }

            // Determine outline.
            let outlines = match pad.geometries.first() {
                Some(geometry) => geometry.to_outlines()?,
                None => Vec::new(),
            };
            let mut outline = outlines.into_iter().next().unwrap_or_default();
            outline.close();
            let mut outline = outline.translated(-hole_offset);
            if pad.mirror_geometry {
                outline = outline.mirrored(Orientation::Horizontal, Point::ORIGIN);
            }
            let outline = outline.rotated(-hole_rotation, Point::ORIGIN);

            // Determine target transform.
            let transform = Transform::new(pad.position, pad.rotation, pad.mirror_geometry);
            let pad_pos = transform.map(&hole_offset);
            let pad_rot = pad.rotation + hole_rotation;

            let mut layers = Vec::new();
            if pad.on_top {
                layers.push(ibom::Layer::Front);
            }
            if pad.on_bottom {
                layers.push(ibom::Layer::Back);
            }
            ibom_pads.push(ibom::Pad::new(
                &layers,
                pos(pad_pos),
                deg(pad_rot),
                &outline.to_svg_path_mm(),
                drill,
                pad.net_name.as_deref(),
                pad.pin1,
            ));
        }
        let mut origin = position;
        if layer == InteractiveHtmlBomLayer::Bottom {
            origin -= Point::new(bottom_right.x + top_left.x, Length::ZERO)
                .rotated(rotation, Point::ORIGIN);
        }
        Ok(self.inner.add_footprint(ibom::Footprint::new(
            layer.into(),
            pos(origin),
            deg(rotation),
            (mm(top_left.x), -mm(bottom_right.y)),
            (mm(bottom_right.x), -mm(top_left.y)),
            fields,
            &ibom_pads,
            mount,
        )))
    }

    /// Adds a BOM row of designators and footprint IDs (upstream
    /// `addBomRow()`).
    pub fn add_bom_row(&mut self, sides: InteractiveHtmlBomSides, parts: &[(String, usize)]) {
        let row = parts
            .iter()
            .map(|(designator, id)| ibom::RefMap::new(designator, *id))
            .collect();
        match sides {
            InteractiveHtmlBomSides::Top => self.inner.bom_front.push(row),
            InteractiveHtmlBomSides::Bottom => self.inner.bom_back.push(row),
            InteractiveHtmlBomSides::Both => self.inner.bom_both.push(row),
        }
    }

    /// Generates the HTML page (upstream `generateHtml()`).
    pub fn generate_html(&self) -> Result<String> {
        self.inner
            .generate_html()
            .map_err(Error::InteractiveHtmlBom)
    }
}
